# -*- coding: utf-8 -*-
"""semantic_telemetry.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wr30WClsweDXdMKe1PHNMAjqI1A9C9GJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sentence_transformers import SentenceTransformer
from sklearn.manifold import TSNE
from sklearn.metrics.pairwise import cosine_similarity
from matplotlib.lines import Line2D
# ==========================================
# 1. START THE ENGINE (Load once to save memory)
# ==========================================
print("Loading linguistic engine (SBERT)...")
model = SentenceTransformer('all-MiniLM-L6-v2')
# ==========================================
# 2. CORE TELEMETRY MATH (Helper Functions)
# ==========================================
def get_centroid_distance(idea_embedding, reference_embeddings):
    """
    Calculates the semantic distance of a single idea's embedding
    from the centroid of a set of reference embeddings.
    A higher score = more distant from the group average = more original.
    """
    if len(reference_embeddings) == 0:
        return 0.0
    centroid = np.mean(reference_embeddings, axis=0).reshape(1, -1)
    return 1.0 - cosine_similarity(idea_embedding.reshape(1, -1), centroid)[0][0]

def get_centroid_shift(emb_t1, emb_t2):
    """Calculates the semantic drift between two sets of embeddings."""
    if len(emb_t1) == 0 or len(emb_t2) == 0: return 0.0
    c1 = np.mean(emb_t1, axis=0).reshape(1, -1)
    c2 = np.mean(emb_t2, axis=0).reshape(1, -1)
    return 1.0 - cosine_similarity(c1, c2)[0][0]

def get_dispersion(embeddings):
    """Calculates the internal spread (divergence) of a set of embeddings."""
    if len(embeddings) < 2: return 0.0
    sim_matrix = cosine_similarity(embeddings)
    upper_triangle = np.triu_indices_from(sim_matrix, k=1)
    return 1.0 - np.mean(sim_matrix[upper_triangle])

def get_novelty(emb_t2, emb_t1):
    """Calculates the minimum distance to past ideas (True Novelty)."""
    if len(emb_t1) == 0 or len(emb_t2) == 0: return 0.0
    cross_sim = cosine_similarity(emb_t2, emb_t1)
    min_dist_to_past = 1.0 - np.max(cross_sim, axis=1)
    return np.mean(min_dist_to_past)

def ingest_and_split(csv_filepath, requires_participants=False):
    """Standardized data intake manifold."""
    df = pd.read_csv(csv_filepath)

    # Check for required columns
    required_cols = ['timeStamp', 'idea']
    if requires_participants:
        required_cols.append('participant_id')

    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"CSV is missing required column: '{col}'")

    df = df.dropna(subset=required_cols)
    df['timeStamp'] = pd.to_datetime(df['timeStamp'])
    df = df.sort_values(by='timeStamp')

    start_time = df['timeStamp'].min()
    midpoint = start_time + pd.Timedelta(minutes=5)
    df['Time_Phase'] = np.where(df['timeStamp'] < midpoint, 'Time 1', 'Time 2')

    return df

# ==========================================
# 3. FULL T-SNE VISUAL PIPELINE
# ==========================================
def run_full_tsne_visual(csv_filepath):
    print(f"\n=== RUNNING FULL t-SNE VISUAL: {csv_filepath} ===")
    df = pd.read_csv(csv_filepath)

    if 'idea' not in df.columns:
        raise ValueError("CSV is missing required column: 'idea'")

    df = df.dropna(subset=['idea'])
    all_ideas = df['idea'].tolist()

    if len(all_ideas) < 2:
        print("\nERROR: Not enough ideas to run t-SNE.")
        return

    print(f"Encoding {len(all_ideas)} ideas into semantic space...")
    embeddings = model.encode(all_ideas)

    perp = min(30, len(all_ideas) - 1)
    tsne_2d = TSNE(n_components=2, perplexity=perp, random_state=42).fit_transform(embeddings)

    plt.figure(figsize=(12, 9))
    plt.scatter(tsne_2d[:, 0], tsne_2d[:, 1], s=150, c='steelblue', alpha=0.7)

    for i, idea in enumerate(all_ideas):
        short_label = " ".join(idea.split()[:3]) + "..."
        plt.annotate(
            short_label,
            (tsne_2d[i, 0], tsne_2d[i, 1]),
            xytext=(5, 5),
            textcoords='offset points',
            fontsize=8
        )

    plt.title("Full Semantic Map: All Ideas", fontweight='bold')
    plt.gca().set_aspect('equal', adjustable='datalim')
    plt.margins(0.2)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.show()

# ==========================================
# 4. GROUP-LEVEL PIPELINE
# ==========================================
def run_group_telemetry(csv_filepath):
    print(f"\n=== RUNNING GROUP PIPELINE: {csv_filepath} ===")
    df = ingest_and_split(csv_filepath, requires_participants=False)

    t1_df = df[df['Time_Phase'] == 'Time 1']
    t2_df = df[df['Time_Phase'] == 'Time 2']

    ideas_t1, ideas_t2 = t1_df['idea'].tolist(), t2_df['idea'].tolist()

    print(f"Time 1 Ideas (0-5 mins): {len(ideas_t1)}")
    print(f"Time 2 Ideas (5-10 mins): {len(ideas_t2)}")

    if len(ideas_t1) < 2 or len(ideas_t2) < 2:
        print("\nERROR: Not enough ideas to run math.")
        return
    print("Encoding ideas into semantic space...")
    emb_t1 = model.encode(ideas_t1)
    emb_t2 = model.encode(ideas_t2)

    # --- Metrics ---
    shift = get_centroid_shift(emb_t1, emb_t2)
    disp1, disp2 = get_dispersion(emb_t1), get_dispersion(emb_t2)
    novelty = get_novelty(emb_t2, emb_t1)

    print("\n--- GROUP TELEMETRY REPORT ---")
    print(f"1. Centroid Shift (Semantic Drift): {shift:.4f}")
    print(f"2. Dispersion Time 1: {disp1:.4f}")
    print(f"   Dispersion Time 2: {disp2:.4f}")
    print(f"   Net Expansion: {disp2 - disp1:+.4f}")
    print(f"3. Avg Novelty of Time 2 Ideas: {novelty:.4f}")
    # --- Plotting ---
    all_ideas = ideas_t1 + ideas_t2
    all_embeddings = np.vstack((emb_t1, emb_t2))
    colors = ['red'] * len(ideas_t1) + ['green'] * len(ideas_t2)

    perp = min(5, len(all_ideas) - 1)
    tsne_2d = TSNE(n_components=2, perplexity=perp, random_state=42).fit_transform(all_embeddings)

    plt.figure(figsize=(10, 8))
    plt.scatter(tsne_2d[:, 0], tsne_2d[:, 1], s=150, c=colors, alpha=0.7)

    for i, idea in enumerate(all_ideas):
        short_label = " ".join(idea.split()[:3]) + "..."
        plt.annotate(short_label, (tsne_2d[i, 0], tsne_2d[i, 1]), xytext=(5, 5), textcoords='offset points')

    plt.title("Group Semantic Evolution: Time 1 (Red) vs. Time 2 (Green)", fontweight='bold')
    plt.gca().set_aspect('equal', adjustable='datalim')
    plt.margins(0.2)
    plt.grid(True, linestyle='--', alpha=0.5)

    legend_elements = [Line2D([0], [0], marker='o', color='w', label='Time 1', markerfacecolor='red', markersize=10),
                       Line2D([0], [0], marker='o', color='w', label='Time 2', markerfacecolor='green', markersize=10)]
    plt.legend(handles=legend_elements, loc='best')
    plt.show()

# ==========================================
# 5. INDIVIDUAL-LEVEL PIPELINE
# ==========================================
def run_individual_telemetry(csv_filepath):
    print(f"\n=== RUNNING INDIVIDUAL PIPELINE: {csv_filepath} ===")
    df = ingest_and_split(csv_filepath, requires_participants=True)

    print("Encoding all ideas to build the Global Semantic Map...")
    all_ideas = df['idea'].tolist()
    all_embeddings = model.encode(all_ideas)

    perp = min(15, len(all_ideas) - 1)
    global_tsne_coords = TSNE(n_components=2, perplexity=perp, random_state=42).fit_transform(all_embeddings)

    df['tSNE_X'] = global_tsne_coords[:, 0]
    df['tSNE_Y'] = global_tsne_coords[:, 1]
    df['embedding'] = list(all_embeddings)

    participants = df['participant_id'].unique()
    cols = 2
    rows = math.ceil(len(participants) / cols)
    fig, axes = plt.subplots(rows, cols, figsize=(15, 6 * rows))
    if len(participants) == 1: axes = [axes] # Handle single participant edge case
    else: axes = axes.flatten()

    for idx, p_id in enumerate(participants):
        p_df = df[df['participant_id'] == p_id]
        t1_df = p_df[p_df['Time_Phase'] == 'Time 1']
        t2_df = p_df[p_df['Time_Phase'] == 'Time 2']

        print(f"\n--- Participant: {p_id} ---")
        print(f"Ideas: {len(t1_df)} (T1) | {len(t2_df)} (T2)")

        if len(t1_df) > 0 and len(t2_df) > 0:
            emb_t1 = np.vstack(t1_df['embedding'].values)
            emb_t2 = np.vstack(t2_df['embedding'].values)

            print(f"Centroid Shift: {get_centroid_shift(emb_t1, emb_t2):.4f}")
            if len(emb_t1) > 1 and len(emb_t2) > 1:
                print(f"Dispersion Change: {get_dispersion(emb_t2) - get_dispersion(emb_t1):+.4f}")
        else:
            print("Metrics: Needs ideas in BOTH time periods to calculate shift.")
        ax = axes[idx]
        ax.scatter(df['tSNE_X'], df['tSNE_Y'], c='lightgray', s=50, alpha=0.3, label='Group Map')
        ax.scatter(t1_df['tSNE_X'], t1_df['tSNE_Y'], c='red', s=150, alpha=0.8, label='Time 1')
        ax.scatter(t2_df['tSNE_X'], t2_df['tSNE_Y'], c='green', s=150, alpha=0.8, label='Time 2')

        if len(t1_df) > 0 and len(t2_df) > 0:
            ax.plot([t1_df['tSNE_X'].mean(), t2_df['tSNE_X'].mean()],
                    [t1_df['tSNE_Y'].mean(), t2_df['tSNE_Y'].mean()],
                    color='black', linestyle='--', linewidth=2, label='Trajectory')

        ax.set_title(f"Participant: {p_id}", fontweight='bold')
        ax.set_aspect('equal', adjustable='datalim')
        ax.margins(0.1)
        ax.legend(loc='best', fontsize='small')
    for i in range(len(participants), len(axes)):
        fig.delaxes(axes[i])

    plt.suptitle("Individual Semantic Trajectories on Global Map", fontsize=18, y=1.02)
    plt.tight_layout()
    plt.show()

# ==========================================
# 6. SINGLE IDEA ORIGINALITY
# ==========================================
def score_idea_originality(idea, csv_filepath):
    """
    Scores a single idea's originality against the centroid of all ideas
    in a reference CSV. Prints distance and contextualizes it against
    the distribution of all ideas in the dataset.
    """
    print(f"\n=== CENTROID ORIGINALITY SCORE ===")
    print(f"Idea: '{idea}'")

    df = pd.read_csv(csv_filepath).dropna(subset=['idea'])
    reference_ideas = df['idea'].tolist()

    print(f"Encoding {len(reference_ideas)} reference ideas + target idea...")
    ref_embeddings = model.encode(reference_ideas)
    idea_embedding = model.encode([idea])[0]

    target_distance = get_centroid_distance(idea_embedding, ref_embeddings)

    # Score every reference idea against the same centroid for context
    all_distances = [
        get_centroid_distance(emb, ref_embeddings)
        for emb in ref_embeddings
    ]

    percentile = np.mean(np.array(all_distances) < target_distance) * 100

    print(f"\nCentroid Distance (target idea): {target_distance:.4f}")
    print(f"Mean centroid distance (all ideas): {np.mean(all_distances):.4f}")
    print(f"Originality Percentile: {percentile:.1f}th percentile")
    print(f"(More original than {percentile:.1f}% of ideas in the dataset)")

    return target_distance

# ==========================================
# 7. EXECUTION BLOCK
# ==========================================
if __name__ == "__main__":
    # How to use this file:
    # Make sure your CSV has the columns: 'timeStamp', 'idea', and (optionally) 'participant_id'

    csv_file = 'ideaData.csv'

    # Uncomment the pipeline you want to run:
    run_full_tsne_visual(csv_file)
    # run_group_telemetry(csv_file)
    # run_individual_telemetry(csv_file)
    # score_idea_originality("Making certain bundles be all inclusive,", csv_file)
    pass